/* Generated By:JJTree: Do not edit this line. ASTButton.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package editor.parser;

public
@SuppressWarnings("all")
class ASTButton extends SimpleNode {
  public ASTButton(int id) {
    super(id);
  }

  public ASTButton(VGLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=3ef86747449d3304a9a58b2606926c11 (do not edit this line) */
