/* Generated By:JJTree: Do not edit this line. ASTCircle.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package editor.parser;

public
@SuppressWarnings("all")
class ASTCircle extends SimpleNode {
  public ASTCircle(int id) {
    super(id);
  }

  public ASTCircle(VGLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6c0e0b80d6f1b1e872a21f5f994e9d5c (do not edit this line) */
