/* Generated By:JJTree: Do not edit this line. ASTFunctionCall.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package editor.parser;

public
@SuppressWarnings("all")
class ASTFunctionCall extends SimpleNode {
  public ASTFunctionCall(int id) {
    super(id);
  }

  public ASTFunctionCall(VGLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d7d6eb2884787e85172032a084e1a997 (do not edit this line) */
