/* Generated By:JJTree: Do not edit this line. ASTIdentifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package editor.parser;

public
@SuppressWarnings("all")
class ASTIdentifier extends SimpleNode {
  public ASTIdentifier(int id) {
    super(id);
  }

  public ASTIdentifier(VGLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=70568b21a89872dd46882779a27b0fa2 (do not edit this line) */
