/* Generated By:JJTree: Do not edit this line. ASTPoint.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=true,VISITOR=false,TRACK_TOKENS=true,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package editor.parser;

public
@SuppressWarnings("all")
class ASTPoint extends SimpleNode {
  public ASTPoint(int id) {
    super(id);
  }

  public ASTPoint(VGLParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=6e0aad3311bddcd79f86b99a19fdde48 (do not edit this line) */
