/* Generated By:JJTree&JavaCC: Do not edit this line. VGLParserConstants.java */
package editor.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface VGLParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 5;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 6;
  /** RegularExpression Id. */
  int HEX_LITERAL = 7;
  /** RegularExpression Id. */
  int OCTAL_LITERAL = 8;
  /** RegularExpression Id. */
  int CANVAS = 9;
  /** RegularExpression Id. */
  int POINT = 10;
  /** RegularExpression Id. */
  int LINE = 11;
  /** RegularExpression Id. */
  int CIRCLE = 12;
  /** RegularExpression Id. */
  int BUTTON = 13;
  /** RegularExpression Id. */
  int ROTATE = 14;
  /** RegularExpression Id. */
  int MESSAGE = 15;
  /** RegularExpression Id. */
  int FUNCTION = 16;
  /** RegularExpression Id. */
  int IDENTIFIER = 17;
  /** RegularExpression Id. */
  int STR_LITERAL = 18;
  /** RegularExpression Id. */
  int LETTER = 19;
  /** RegularExpression Id. */
  int DIGIT = 20;
  /** RegularExpression Id. */
  int EOL = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "<token of kind 3>",
    "<token of kind 4>",
    "<INTEGER_LITERAL>",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<OCTAL_LITERAL>",
    "\"CANVAS\"",
    "\"POINT\"",
    "\"LINE\"",
    "\"CIRCLE\"",
    "\"BUTTON\"",
    "\"ROTATE\"",
    "\"MESSAGE\"",
    "\"FUNCTION\"",
    "<IDENTIFIER>",
    "<STR_LITERAL>",
    "<LETTER>",
    "<DIGIT>",
    "<EOL>",
    "\"()\"",
    "\"{\"",
    "\"}\"",
    "\".\"",
  };

}
