/* Generated By:JavaCC: Do not edit this line. VGLParserTreeConstants.java Version 5.0 */
package editor.parser;

public interface VGLParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTPOINT = 2;
  public int JJTCANVAS = 3;
  public int JJTCIRCLE = 4;
  public int JJTLINE = 5;
  public int JJTBUTTON = 6;
  public int JJTFUNCTIONCALL = 7;
  public int JJTFUNCTIONDEF = 8;
  public int JJTIDENTIFIER = 9;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "Point",
    "Canvas",
    "Circle",
    "Line",
    "Button",
    "FunctionCall",
    "FunctionDef",
    "Identifier",
  };
}
/* JavaCC - OriginalChecksum=f5df4f452307e31f2f533d195e08ff54 (do not edit this line) */
